# Generated by Django 4.0.5 on 2022-06-15 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_c', models.CharField(max_length=30)),
                ('auspiciante', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_e', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=30)),
                ('usu_twitter', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_j', models.CharField(max_length=30)),
                ('posicion', models.CharField(max_length=30)),
                ('numero', models.IntegerField(verbose_name='numero de jugador')),
                ('sueldo', models.IntegerField(verbose_name='sueldo de jugador')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='futbolec.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='C_equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('equipo', models.CharField(max_length=30)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonato', to='futbolec.campeonato')),
            ],
        ),
    ]
