# Generated by Django 4.0.1 on 2022-06-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbolec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_equipos',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_equipos', to='futbolec.campeonato'),
        ),
        migrations.AlterField(
            model_name='c_equipos',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_equipos', to='futbolec.equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='futbolec.equipo'),
        ),
    ]
